---
version: "3.9"
services:
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
  db:
    ports:
      - 5432:5432
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./db/script:/script:ro
  backend:
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://idc:password@db:5432/idh_idc
      - CLIENT_ID=test
      - CLIENT_SECRET=test
    network_mode: service:mainnetwork
    image: python:3.10.7
    command: ["./dev.sh"]
    volumes:
      - ./backend:/app:delegated
    working_dir: /app
  frontend:
    image: akvo/akvo-node-18-alpine:20230831.105309.b9593b7
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    depends_on:
      - backend
volumes:
  pg-data:
