name: IDH-IDC Release Pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout Akvo composite actions
        uses: actions/checkout@v4
        with:
          repository: akvo/composite-actions
          token: ${{ secrets.GH_PAT }}
          path: composite-actions
          ref: 0.0.10

      - name: Node Operations
        uses: ./composite-actions/.github/actions/node-operation
        with:
          node-version: "18"
          node-command: "yarn install --no-progress --frozen-lock && yarn build && rm -rf node_modules"

      - name: Docker Build Frontend
        uses: ./composite-actions/.github/actions/docker-build
        with:
          app-name: "idh-idc"
          service-name: "frontend"
          dockerfile-location: "frontend"
          cluster-name: "production"

      - name: Docker Build Backend
        uses: ./composite-actions/.github/actions/docker-build
        with:
          app-name: "idh-idc"
          service-name: "backend"
          dockerfile-location: "backend"
          cluster-name: "production"

      - name: Docker Push Frontend
        uses: ./composite-actions/.github/actions/docker-push
        with:
          app-name: "idh-idc"
          service-name: "frontend"
          gcloud-sa: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_REGISTRY }}
          cluster-name: "production"

      - name: Docker Push Backend
        uses: ./composite-actions/.github/actions/docker-push
        with:
          app-name: "idh-idc"
          service-name: "backend"
          gcloud-sa: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_REGISTRY }}
          cluster-name: "production"

      - name: Rollout Frontend
        uses: ./composite-actions/.github/actions/k8s-rollout
        with:
          app-name: "idh-idc"
          deployment-name: "idh-idc"
          container-name: "frontend"
          cluster-name: "production"
          namespace-name: "default"
          gcloud-sa: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_K8S }}

      - name: Rollout Backend
        uses: ./composite-actions/.github/actions/k8s-rollout
        with:
          app-name: "idh-idc"
          deployment-name: "idh-idc"
          container-name: "backend"
          cluster-name: "production"
          namespace-name: "default"
          gcloud-sa: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_K8S }}
